mysite/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views
from experts import views as experts_views
from experts import views_update as update_views
from projects import views as projects_views
from clients import views as clients_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('dashboard/', user_views.dashboard, name='dashboard'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='users/password_change_form.html'), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'), name='password_change_done'),
    path('password_rest/',
         auth_views.PasswordResetView.as_view(template_name='users/password_reset_form.html'),
         name='password_reset'),
    path('password_rest/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),


    path('', include('projects.urls')),
    path('', include('clients.urls')),
    path('', include('experts.urls')),
    path('', include('users.urls')),

]

"""
    path('expert_contact_info/<str:ename>/<int:eid>/', experts_views.expert_contact_info, name='expert_contact_info'),
path('addeworkexp/', experts_views.addWorkexp, name='addworkexp'),
    path('addecomment/', experts_views.addComment, name='addcomment'),
path('addexperttodatabase/', experts_views.addExpertToDatabase, name='addexperttodatabase'),
path('projects/', projects_views.project, name='project_base'),
    path('projects_list/', projects_views.projectInfo_list, name='project_info_list'),
    path('add_project/', projects_views.add_project, name='add_project'),
    path('addProjectToDatabase/', projects_views.addProjectToDatabase, name='addProjectToDatabase'),
     path('clients/', clients_views.client, name='client_base'),
    
path('export_all_excel/', experts_views.export_all_excel, name='export_all_excel'),
path('addworkexptodatabase/', experts_views.addWorkexpToDatabase, name='addworkexptodatabase'),
path('addcommenttodatabase/<str:ename>/<str:emobile>/', experts_views.addCommentToDatabase, name='addcommenttodatabase'),
 path('update/<int:eid>/<str:ename>/commentdetail/', experts_views.comment_detail_update, name='comment_detail_update'),
path('updateomment', update_views.commentUpdate, name='updatecomment'),
    path('updateworkexp/', update_views.workexpUpdate, name='updateworkexp'),
   
path('update/<int:eid>/<str:ename>/workexpdetail/', experts_views.workexp_detail_update, name='workexp_detail_update'),
    path('workexpupdatetodatabase/', update_views.workexpUpdateToDatabase, name='workexpupdatetodatabase'),
path('update/<int:eid>/<str:ename>/commentdetail/', experts_views.comment_detail_update, name='comment_detail_update'),
    path('commentupdatetodatabase/', update_views.commentUpdateToDatabase, name='commentupdatetodatabase'),

"""
"""
path('addexpert/', experts_views.addExpert, name='addexpert'),
    path('home/', experts_views.base, name='home'),




    path('addcomment/<int:eid>/<str:ename>/', experts_views.add_comment, name='add_comment'),
    path('addworkexp/<int:eid>/<str:ename>/', experts_views.add_workexp, name='add_workexp'),

    path('addcomplete/', experts_views.addok, name='addcomplete'),


    path('updateexpert/', update_views.expertInfoUpdate, name='updateexpert'),
    path('expertinfolist/', experts_views.expertInfo_list, name='expertinfolist'),
    path('<str:ename>/<int:eid>/', experts_views.expert_detail, name='expert_detail'),
    path('update/<str:ename>/<int:eid>/', experts_views.expert_detail_update, name='expert_detail_update'),
    path('contact_info_update/<str:ename>/<int:eid>/', experts_views.expert_contact_info_update, name='expert_contact_info_update'),
    path('expertinfoupdatetodatabase/', update_views.expertInfoUpdateToDatabase, name='expertinfoupdatetodatabase'),

    path('<int:eid>/<str:ename>/commentdetail/', experts_views.comment_detail, name='comment_detail'),
    path('update/<int:eid>/<int:cmtid>/commentdetail/', experts_views.comment_detail_update, name='comment_detail_update'),

    path('<int:eid>/<str:ename>/workexpdetail/', experts_views.workexp_detail, name='workexp_detail'),
    path('update/<int:eid>/<int:expid>/workexpdetail/', experts_views.workexp_detail_update, name='workexp_detail_update'),

    path('deleteexpert/', update_views.expertInfoDelete, name='deleteexpert'),
    path('delete_confirm/<int:eid>/<str:ename>/', experts_views.delete_confirm, name='delete_confirm'),
    path('delete/<int:eid>/<str:ename>/', experts_views.myDelete, name='myDelete'),
    path('expertinfodeletefromdatabase/', update_views.expertInfoDeleteFromDatabase, name='expertinfodeletefromdatabase'),

    path('deletecomment/<int:eid>/<int:cmtid>/', update_views.delete_comment, name='delete_comment'),
    path('deleteworkexp/<int:eid>/<int:expid>/', update_views.delete_workexp, name='delete_workexp'),
    path('deleteworkexpconfirm/<int:eid>/<int:expid>/', update_views.delete_workexp_confirm, name='delete_workexp_confirm'),
    path('deletecommentconfirm/<int:eid>/<int:cmtid>/', update_views.delete_comment_confirm, name='delete_comment_confirm'),

    path('search_expert/', experts_views.search_expert, name='search_expert'),
    path('advanced_expert_search/', experts_views.advanced_expert_search, name='advanced_expert_search'),
    path('advanced_expert/', experts_views.advanced_expert_form, name='advanced_expert_form'),

    path('expert_payment/<int:ep_id>/edit', experts_views.get_payment_update, name='get_payment_update'),


"""

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    #
    #path('login/', views.user_login, name='login'),
    #path('login/',auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    #path('logout/',auth_views.LogoutView.as_view(), name='logout'),
    #path('dashboard/', views.dashboard, name='dashboard'),
    #path('register/',views.register, name='register'),
    #path('login/',views.login, name='login'),
    #path('logout/', views.user_logout, name='logout'),
    #path('dashboard/', views.dashboard, name='dashboard'),
    #path('logout/',auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
]

experts/models.py
# Create your models here.
from django.db import models
from django.urls import reverse
from django.shortcuts import render



class ExpertInfo(models.Model):
    eid = models.AutoField(primary_key=True)
    ename = models.CharField(max_length=150, blank=True, null=True)
    esex = models.CharField(max_length=10, choices=[('M', '男'), ('F', '女'), ('X','未知')], default='X')
    emobile = models.CharField(max_length=150, blank=True, null=True)
    eemail = models.CharField(max_length=150, blank=True, null=True)
    etrade = models.CharField(max_length=150, blank=True, null=True)
    esubtrade = models.CharField(max_length=150, blank=True, null=True)
    elocation = models.CharField(max_length=150, blank=True, null=True)
    eqq = models.CharField(max_length=150, blank=True, null=True)
    estate = models.IntegerField(blank=True, null=True)
    ecomefrom = models.TextField(blank=True, null=True)
    eremark = models.TextField(blank=True, null=True)
    addtime = models.DateTimeField(auto_now_add=True)
    ebackground = models.TextField(blank=True, null=False)
    efee = models.FloatField(blank=True,null=False,default=0.0,verbose_name='专家付费单价')
    eupdated_by = models.CharField(max_length=150, blank=True, null=True)
    interview_num = models.IntegerField(blank=True,null=True,default=0)

    class Meta:
        managed = True
        ordering = ('-addtime',)
        db_table = 'expert_info'
    def __str__(self):
        return "{}-{}".format(self.eid, self.ename)

    def contact_info(self):
        #print("==============models.contact_info============", self.ename,self.eid)
        #print(reverse('expert_contact_info', args=[self.eid]))
        return reverse('expert_contact_info', args=[self.ename,self.eid])

    def expert_contact_info_update(self):
        #print("==============models.expert_contact_info_update============", self.ename, self.eid)
        return reverse('expert_contact_info_update', args=[self.ename, self.eid])

    def myDelete(self):
        #print("==============models.delete============",self.eid, self.ename)
        return reverse('myDelete',args=[self.eid, self.ename])

    def delete_confirm_url(self):
        #print("==============models.delete_confirm_url============",self.eid, self.ename)
        return reverse('delete_confirm',args=[self.eid, self.ename])

    def get_absolute_url(self):
        return reverse('expert_detail',args=[self.ename, self.eid])

    def get_comment_url(self):
        #print("==============models.get_comment_url============",self.eid, self.ename)
        return reverse('comment_detail',args=[self.eid, self.ename])

    def add_comment_url(self):
        return reverse('add_comment',args=[self.eid,self.ename])

    def get_workexp_url(self):
        #print("==============models.get_workexp_url============", self.eid, self.ename)
        return reverse('workexp_detail',args=[self.eid, self.ename])

    def add_workexp_url(self):
        return reverse('add_workexp',args=[self.eid,self.ename])

    def get_update_url(self):
        return reverse('expert_detail_update', args=[self.ename, self.eid])

    def get_company(self):
        #print("==============models.get_workexp============")
        work_list = WorkExp.objects.filter(eid=self.eid)
        if len(work_list) == 0:
            return "无"
        else:
            #l = [work_list[0].company, work_list[0].position]
            #return ('-').join(l)
            #result = ('；').join([(work.company,work.position).__str__() for work in work_list])
            return work_list[0].company

    def get_position(self):
        #print("==============models.get_workexp============")
        work_list = WorkExp.objects.filter(eid=self.eid)
        if len(work_list) == 0:
            return "无"
        else:
            #l = [work_list[0].company,work_list[0].position]
            return work_list[0].position
            #result = ('；').join([work.position for work in work_list])
            #return result

    def get_duty(self):
        #print("==============models.get_workexp============")
        work_list = WorkExp.objects.filter(eid=self.eid)
        if len(work_list) == 0:
            return "无"
        else:
            #l = [work_list[0].company,work_list[0].position]
            return work_list[0].duty
            #result = ('；').join([work.position for work in work_list])
            #return result

    def get_expert_score(self):
        from projects.models import Project2Expert
        interviews = Project2Expert.objects.filter(eid=self.eid)
        total = 0.0
        num = 0
        for itv in interviews:
            if itv.status == 1:
                total += itv.avg_score
                num += 1
        if num == 0:
            return 0
        else:
            score = round(total / num, 2)
            return score

class ExpertComments(models.Model):

    cmtid = models.AutoField(primary_key=True)
    eid = models.ForeignKey('ExpertInfo', models.DO_NOTHING, db_column='eid')
    eproblem = models.TextField(blank=True, null=True)
    ecomment = models.TextField(blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'expert_comments'

    def __str__(self):
        # 默认的人们可读的对象表达方式
        return "{}-{}".format(self.eid,self.eproblem)


    # 刚加的
    def get_comment_update_url(self):
        #print("==========在models.py中的 get_comment_update_url()")
        num = self.eid.eid
        #print(type(num))
        return reverse('comment_detail_update', args=[num,self.cmtid ])

    def delete_comment(self):
        #print("==========在models.py中的 delete_comment()")
        num = self.eid.eid
        #print(type(num))
        return reverse('delete_comment', args=[num,self.cmtid ])

    def delete_comment_confirm(self):
        #print("==========在models.py中的 delete_comment_confirm()")
        num = self.eid.eid
        #print(type(num))
        return reverse('delete_comment_confirm', args=[num,self.cmtid ])
    """
    def get_comment_url(self):
        return reverse('comment_detail',args=[self.eid,])
    """

class WorkExp(models.Model):
    expid = models.AutoField(primary_key=True)
    eid = models.ForeignKey(ExpertInfo, models.DO_NOTHING, db_column='eid')
    stime = models.CharField(max_length=150,blank=True, null=True)
    etime = models.CharField(max_length=150,blank=True, null=True)
    company = models.CharField(max_length=250, blank=True, null=True)
    agency = models.CharField(max_length=150, blank=True, null=True)
    position = models.CharField(max_length=150, blank=True, null=True)
    duty = models.TextField(blank=True, null=True)
    area = models.TextField(blank=True, null=True)

    class Meta:
        managed = True
        ordering = ('-stime',)
        db_table = 'work_exp'

    def __str__(self):
        return "{}-{}".format(self.company,self.position)

    def get_workexp_update_url(self):
        #print("==========在models.py中的 get_workexp_update_url()")
        num = self.eid.eid
        return reverse('workexp_detail_update', args=[num, self.expid])

    def delete_workexp(self):
        #print("==========在models.py中的 delete_workexp()")
        num = self.eid.eid
        return reverse('delete_workexp', args=[num, self.expid])

    def delete_workexp_confirm(self):
        #print("==========在models.py中的 delete_workexp_confirm()")
        num = self.eid.eid
        return reverse('delete_workexp_confirm', args=[num, self.expid])


class Payment(models.Model):
    # F. Expert_Payment
    ep_id = models.AutoField(primary_key=True)
    eid = models.ForeignKey(ExpertInfo, on_delete=models.CASCADE)
    alipay = models.CharField(max_length=150, blank=True, null=True, verbose_name='支付宝')
    bank = models.CharField(max_length=250, blank=True, null=True, verbose_name='银行账号')
    wechat = models.CharField(max_length=150, blank=True, null=True, verbose_name='微信支付')
    remark = models.TextField(blank=True, null=True, verbose_name='备注')

    class Meta:
        managed = True
        db_table = 'payment'

    def __str__(self):
        return "{}-{}".format(self.ep_id,self.eid)

    def get_payment_update(self):
        #print("==========在models.py中的 get_payment_update()")

        return reverse('get_payment_update', args=[self.ep_id,])

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class LoginForm(forms.Form):
    username = forms.CharField()
    #email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1','password2']

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Your account has been created! You are now able to log in')
            return redirect('login')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form})


@login_required
def dashboard(request):
    return render(request, 'users/dashboard.html')

users/templates/users/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-cn">
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'experts/main.css' %}">


</head>
<body>
   <header class="site-header">
       <nav class="navbar navbar-expand-sm navbar-dark bg-dark" style="height: 50px">
        <a class="navbar-brand" href="{% url 'home' %}">LeapTech</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample01" aria-controls="navbarsExample01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
{% if user.is_authenticated %}
  <div class="collapse navbar-collapse" id="navbarsExample01">
    <ul class="navbar-nav mr-auto">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">专家</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
                <a class="dropdown-item" href="{% url 'advanced_expert_form'%}">查找专家</a>
                <a class="dropdown-item" href="{% url 'expertinfolist' %}">专家列表</a>
                <a class="dropdown-item" href="{% url 'addexpert'%}">添加专家</a>
                <a class="dropdown-item" href="{% url 'updateexpert' %}">更新专家</a>
            </div>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="dropdown02" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">项目</a>
            <div class="dropdown-menu" aria-labelledby="dropdown02">
                <a class="dropdown-item" href="{% url 'project_info_list' %}">项目列表</a>
                <a class="dropdown-item" href="{% url 'advanced_project_form' %}">查找项目</a>
                <!--<a class="dropdown-item" href="{% url 'add_project' %}">添加项目</a>-->
            </div>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="dropdown03" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">客户</a>
            <div class="dropdown-menu" aria-labelledby="dropdown03">
                {% if perms.users.can_view_client_info %}
                <a class="dropdown-item" href="{% url 'client_info_list' %}">客户列表</a>
                <a class="dropdown-item" href="{% url 'advanced_client_form' %}">查找客户</a>
                {% endif %}
                {% if perms.users.can_add_client %}
                <a class="dropdown-item" href="{% url 'add_client' %}">添加客户</a>
                {% endif %}
            </div>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">账单</a>
            <div class="dropdown-menu" aria-labelledby="dropdown04">
                {% if perms.users.can_view_cfee %}
                <a class="dropdown-item" href="{% url 'client_interview_info_list' %}">客户账单</a>
                {% endif %}
                {% if perms.users.can_view_project_interview or perms.users.can_view_all_project_interview %}
                <a class="dropdown-item" href="{% url 'interview_info_list' %}">专家账单</a>
                {% endif %}
            </div>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'dashboard' %}">个人中心</a>
        </li>
    </ul>
    <!--<form class="form-inline my-2 my-md-0" method="get" action="{% url 'search_expert' %}">
        {% csrf_token %}
      <input style="height: 35px" class="form-control" type="text" aria-label="Search" name='q' placeholder="专家-全局搜索" required>
    </form>-->
      {% endif %}
      <ul class="navbar-nav">
                <li class="nav-item"><a class="nav-link">{{user.username}}</a></li>

            </ul>
      <ul>
           {% if user.is_authenticated %}
           <li class="nav-item" style="margin-top: 15px">
               <button class="btn btn-outline-danger btn-sm" onclick="location.href='{% url 'logout' %}'">登出</button>
           </li>

           {% endif %}
       </ul>
  </div>
</nav>






    <main role="main" class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
            {% endfor %}
          {% endif %}
            <br><br>
            {% block content %}
            <br><br>
            {% endblock %}
        </div>

      </div>
    </main>
    <br><br><br><br>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

</html->

users/templates/users/dashboard.html
{% extends "users/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container-fluid">

    <div class="media">

        <div class="media-body">

            <h3 class="page-name">个人中心</h3>
            <br>
            <div class="list-group">
                <button type="button" class="list-group-item list-group-item-action" onclick="location.href='.'">Welcome, {{ user.username }}</button>
                <!-- <button type="button" class="list-group-item list-group-item-action" onclick="location.href='{% url 'password_change' %}'">修改密码</button>-->

                <a>
                    <div class="control-group">
                        <table class="table table table-bordered" border="0" width="100%" style="font-size:10px;table-layout: auto">
                            <caption></caption>
                            <thead style="background-color: whitesmoke">
                            <tr style="text-align: center">
                                <th><strong>权限明细</strong></th>
                                <th>添加</th>
                                <th>删除</th>
                                <th>更改</th>
                                <th>查看</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr style="text-align: center">
                                <td>专家基本信息</td>
                                <td>{% if not perms.experts.add_expertinfo %} - {% else %} 有权限 {% endif %}</td>
                                <td>{% if not perms.experts.delete_expertinfo %} - {% else %} 有权限 {% endif %}</td>
                                <td>{% if not perms.experts.change_expertinfo %} - {% else %} 有权限 {% endif %}</td>
                                <td>{% if not perms.experts.view_expertinfo %} - {% else %} 有权限 {% endif %}</td>
                            </tr>
                            <tr style="text-align: center">
                                <td>专家联系方式</td>
                                <td>{% if not perms.users.can_change_expert_contact_info %} - {% else %} 有权限 {% endif %}</td>
                                <td>{% if not perms.users.can_change_expert_contact_info %} - {% else %} 有权限 {% endif %}</td>
                                <td>{% if not perms.users.can_change_expert_contact_info %} - {% else %} 有权限 {% endif %}</td>
                                <td>{% if not perms.users.can_view_expert_contact_info %} - {% else %} 有权限 {% endif %}</td>
                            </tr>
                            <tr style="text-align: center">
                                <td>项目基本信息</td>
                                <td>{% if not perms.projects.add_project %} - {% else %} 有权限 {% endif %}</td>
                                <td>{% if not perms.projects.delete_project %} - {% else %} 有权限 {% endif %}</td>
                                <td>{% if not perms.projects.change_project %} - {% else %} 有权限 {% endif %}</td>
                                <td>{% if not perms.projects.view_project %} - {% else %} 有权限 {% endif %}</td>
                            </tr>
                            <tr style="text-align: center">
                                <td>项目访谈信息</td>
                                <td>{% if not perms.users.can_add_project_interview_1 %} - {% else %} 有权限 {% endif %}</td>
                                <td>{% if not perms.users.can_delete_project_interview %} - {% else %} 有权限 {% endif %}</td>
                                <td>{% if perms.users.can_change_all_project_interview %} 有权限 {% elif perms.users.can_change_project_interview %} 部分权限 {% else %} - {% endif %}</td>
                                <td>{% if perms.users.can_view_all_project_interview %} 有权限 {% elif perms.users.can_view_project_interview%} 部分权限 {% else %} - {% endif %}</td>
                            </tr>
                            <tr style="text-align: center">
                                <td>客户基本信息</td>
                                <td>{% if not perms.users.can_add_client %} - {% else %} 有权限 {% endif %}</td>
                                <td>{% if not perms.users.can_delete_client_info %} - {% else %} 有权限 {% endif %}</td>
                                <td>{% if not perms.users.can_change_client_info %} - {% else %} 有权限 {% endif %}</td>
                                <td>{% if not perms.users.can_view_client_info %} - {% else %} 有权限 {% endif %}</td>
                            </tr>
                            <tr style="text-align: center">
                                <td>客户联系方式</td>
                                <td>{% if not perms.users.can_add_client_bc_fc %} - {% else %} 有权限 {% endif %}</td>
                                <td>{% if not perms.users.can_delete_client_bc_fc_contact %} - {% else %} 有权限 {% endif %}</td>
                                <td>{% if not perms.users.can_change_client_bc_fc_contact %} - {% else %} 有权限 {% endif %}</td>
                                <td>{% if not perms.users.can_view_client_bc_fc_contact %} - {% else %} 有权限 {% endif %}</td>
                            </tr>
                            <tr style="text-align: center">
                                <td>客户咨费信息</td>
                                <td>{% if not perms.users.can_view_cfee %} - {% else %} 有权限 {% endif %}</td>
                                <td>{% if not perms.users.can_change_cfee %} - {% else %} 有权限 {% endif %}</td>
                                <td>{% if not perms.users.can_change_cfee %} - {% else %} 有权限 {% endif %}</td>
                                <td>{% if not perms.users.can_view_cfee %} - {% else %} 有权限 {% endif %}</td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </a>
            </div>
            <!--{{ user.get_group_permissions}}-->
        </div>

    </div>
    <br>
    <!-- FORM HERE -->
</div>
<div class="border-top pt-3">
    <small class="text-muted">
        <p class="text-secondary">Welcome, {{ user.username }}</p>
    </small>
</div>
{% endblock content %}

users/templates/users/login.html
{% extends "users/base.html" %}
{% load static %}

{% load crispy_forms_tags %}
{% block content %}
<div class="container">

    <h3>Log In</h3>
    <div content-section">
        <form class="form-horizontal" action="." method="post">
              <div class="control-group">
                {{ form.as_p }}
              </div>
            {% csrf_token %}

            <p><input class="btn btn-success btn-sm" type="submit" value="Submit"></p>
        </form>
        <!--<div class="border-top pt-3">
            <small class="text-muted">
                <a class="ml-2" href="{% url 'password_reset' %}"> 忘记密码?</a>
            </small>
        </div>-->
    </div>
{% endblock %}

users/templates/users/logout.html
{% extends "users/base.html" %}
{% block content %}
    <div class="col-sm-10">
      <div class="alert alert-danger" role="alert">
        您已经退出登录, 需要重新登录请点击
          <a href="{% url 'dashboard' %}">登录</a>。

      </div>
    </div>

{% endblock content %}

users/templates/users/password_change_done.html
{% extends "users/base.html" %}
{% block content %}
    <h1>Password changed </h1>
    <p>Your password has been successfully changed.</p>
{% endblock content %}