clients/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('clients/', views.client, name='client_base'),
    path('client_info_list/', views.client_info_list, name='client_info_list'),
    path('add_client/', views.add_client, name='add_client'),

    path('addClientToDatabase/', views.addClientToDatabase, name='addClientToDatabase'),
    path('clients/<int:cid>/detail', views.client_detail, name='client_detail'),

    path('clients/update/<int:cid>/', views.update_client_detail, name='update_client_detail'),

    path('clients/client_add_project/<int:cid>/', views.client_add_project, name='client_add_project'),

    path('clients/client_add_bc/<int:cid>/', views.client_add_bc, name='client_add_bc'),
    path('clients/client_add_fc/<int:cid>/', views.client_add_fc, name='client_add_fc'),

    path('clients/bc_detail_update/<int:bc_id>/<int:cid>', views.bc_detail_update, name='bc_detail_update'),
    path('clients/fc_detail_update/<int:fc_id>/<int:cid>', views.fc_detail_update, name='fc_detail_update'),

    path('clients/delete_client/<int:cid>/', views.delete_client, name='delete_client'),
    path('clients/delete_client_bc/<int:bc_id>/<int:cid>/', views.delete_client_bc, name='delete_client_bc'),
    path('clients/delete_client_fc/<int:fc_id>/<int:cid>/', views.delete_client_fc, name='delete_client_fc'),

    path('clients/advanced_client/', views.advanced_client_form, name='advanced_client_form'),
    path('clients/search_client/', views.advanced_client_search, name='advanced_client_search'),
]

mysite/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views
from experts import views as experts_views
from experts import views_update as update_views
from projects import views as projects_views
from clients import views as clients_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('dashboard/', user_views.dashboard, name='dashboard'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='users/password_change_form.html'), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'), name='password_change_done'),
    path('password_rest/',
         auth_views.PasswordResetView.as_view(template_name='users/password_reset_form.html'),
         name='password_reset'),
    path('password_rest/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),


    path('', include('projects.urls')),
    path('', include('clients.urls')),
    path('', include('experts.urls')),
    path('', include('users.urls')),

]

"""
    path('expert_contact_info/<str:ename>/<int:eid>/', experts_views.expert_contact_info, name='expert_contact_info'),
path('addeworkexp/', experts_views.addWorkexp, name='addworkexp'),
    path('addecomment/', experts_views.addComment, name='addcomment'),
path('addexperttodatabase/', experts_views.addExpertToDatabase, name='addexperttodatabase'),
path('projects/', projects_views.project, name='project_base'),
    path('projects_list/', projects_views.projectInfo_list, name='project_info_list'),
    path('add_project/', projects_views.add_project, name='add_project'),
    path('addProjectToDatabase/', projects_views.addProjectToDatabase, name='addProjectToDatabase'),
     path('clients/', clients_views.client, name='client_base'),
    
path('export_all_excel/', experts_views.export_all_excel, name='export_all_excel'),
path('addworkexptodatabase/', experts_views.addWorkexpToDatabase, name='addworkexptodatabase'),
path('addcommenttodatabase/<str:ename>/<str:emobile>/', experts_views.addCommentToDatabase, name='addcommenttodatabase'),
 path('update/<int:eid>/<str:ename>/commentdetail/', experts_views.comment_detail_update, name='comment_detail_update'),
path('updateomment', update_views.commentUpdate, name='updatecomment'),
    path('updateworkexp/', update_views.workexpUpdate, name='updateworkexp'),
   
path('update/<int:eid>/<str:ename>/workexpdetail/', experts_views.workexp_detail_update, name='workexp_detail_update'),
    path('workexpupdatetodatabase/', update_views.workexpUpdateToDatabase, name='workexpupdatetodatabase'),
path('update/<int:eid>/<str:ename>/commentdetail/', experts_views.comment_detail_update, name='comment_detail_update'),
    path('commentupdatetodatabase/', update_views.commentUpdateToDatabase, name='commentupdatetodatabase'),

"""
"""
path('addexpert/', experts_views.addExpert, name='addexpert'),
    path('home/', experts_views.base, name='home'),




    path('addcomment/<int:eid>/<str:ename>/', experts_views.add_comment, name='add_comment'),
    path('addworkexp/<int:eid>/<str:ename>/', experts_views.add_workexp, name='add_workexp'),

    path('addcomplete/', experts_views.addok, name='addcomplete'),


    path('updateexpert/', update_views.expertInfoUpdate, name='updateexpert'),
    path('expertinfolist/', experts_views.expertInfo_list, name='expertinfolist'),
    path('<str:ename>/<int:eid>/', experts_views.expert_detail, name='expert_detail'),
    path('update/<str:ename>/<int:eid>/', experts_views.expert_detail_update, name='expert_detail_update'),
    path('contact_info_update/<str:ename>/<int:eid>/', experts_views.expert_contact_info_update, name='expert_contact_info_update'),
    path('expertinfoupdatetodatabase/', update_views.expertInfoUpdateToDatabase, name='expertinfoupdatetodatabase'),

    path('<int:eid>/<str:ename>/commentdetail/', experts_views.comment_detail, name='comment_detail'),
    path('update/<int:eid>/<int:cmtid>/commentdetail/', experts_views.comment_detail_update, name='comment_detail_update'),

    path('<int:eid>/<str:ename>/workexpdetail/', experts_views.workexp_detail, name='workexp_detail'),
    path('update/<int:eid>/<int:expid>/workexpdetail/', experts_views.workexp_detail_update, name='workexp_detail_update'),

    path('deleteexpert/', update_views.expertInfoDelete, name='deleteexpert'),
    path('delete_confirm/<int:eid>/<str:ename>/', experts_views.delete_confirm, name='delete_confirm'),
    path('delete/<int:eid>/<str:ename>/', experts_views.myDelete, name='myDelete'),
    path('expertinfodeletefromdatabase/', update_views.expertInfoDeleteFromDatabase, name='expertinfodeletefromdatabase'),

    path('deletecomment/<int:eid>/<int:cmtid>/', update_views.delete_comment, name='delete_comment'),
    path('deleteworkexp/<int:eid>/<int:expid>/', update_views.delete_workexp, name='delete_workexp'),
    path('deleteworkexpconfirm/<int:eid>/<int:expid>/', update_views.delete_workexp_confirm, name='delete_workexp_confirm'),
    path('deletecommentconfirm/<int:eid>/<int:cmtid>/', update_views.delete_comment_confirm, name='delete_comment_confirm'),

    path('search_expert/', experts_views.search_expert, name='search_expert'),
    path('advanced_expert_search/', experts_views.advanced_expert_search, name='advanced_expert_search'),
    path('advanced_expert/', experts_views.advanced_expert_form, name='advanced_expert_form'),

    path('expert_payment/<int:ep_id>/edit', experts_views.get_payment_update, name='get_payment_update'),


"""

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    #
    #path('login/', views.user_login, name='login'),
    #path('login/',auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    #path('logout/',auth_views.LogoutView.as_view(), name='logout'),
    #path('dashboard/', views.dashboard, name='dashboard'),
    #path('register/',views.register, name='register'),
    #path('login/',views.login, name='login'),
    #path('logout/', views.user_logout, name='logout'),
    #path('dashboard/', views.dashboard, name='dashboard'),
    #path('logout/',auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
]

projects/models.py
from django.db import models
from experts.models import ExpertInfo,Payment
from clients.models import Client
from django.urls import reverse


# Create your models here.
class Project(models.Model):
    # B. Project: 一个项目有多个专家,一个专家参与多个项目
    pid = models.AutoField(primary_key=True)
    pname = models.CharField(max_length=250, blank=True, null=True, verbose_name='项目名称')
    cid = models.ForeignKey(Client, on_delete=models.CASCADE, to_field='cid')
    pm = models.CharField(max_length=150, blank=True, null=True, verbose_name='项目经理')
    pcreatetime = models.CharField(max_length=150, blank=True, null=True)
    pdeadline = models.CharField(max_length=150, blank=True, null=True)
    premark = models.TextField(blank=True,null=True)
    pdetail = models.TextField(blank=True,null=True)
    person_in_charge = models.CharField(max_length=150, blank=True, null=True, verbose_name='我方项目对接人')
    expertinfos = models.ManyToManyField(ExpertInfo, through='Project2Expert')

    class Meta:
        managed = True
        ordering = ('-pcreatetime','pdeadline')
        db_table = 'project_info'


    def __str__(self):
        return "{}-{}".format(self.pid, self.pname)

    def get_project_detail(self):
        return reverse('project_detail',args=[self.pid,self.cid.cid])

    def add_p2e(self):
        #print("==========projects/models.add_p2e")
        return reverse('add_p2e',args=[self.pid,])

    def update_project_detail(self):
        #print("==========projects/models.update_project_detail========")
        return reverse('update_project_detail', args=[self.pid,])

    def delete_project(self):
        return reverse('delete_project', args=[self.pid,])

    def pm_contact_info_update(self):
        return reverse('pm_contact_info_update', args=[self.pid,])

    def get_client_name(self):
        return self.cid.cname


class Project2Expert(models.Model):
    # 访谈信息表
    # B. Project: 一个项目有多个专家
    # A-B. Project2Experts：多对多
    pteid = models.AutoField(primary_key=True)
    pid = models.ForeignKey(Project, on_delete=models.CASCADE)
    eid = models.ForeignKey(ExpertInfo, on_delete=models.CASCADE)
    status = models.IntegerField(choices=[(1, '已访谈'), (0, '未访谈')], default=0, verbose_name='访谈状态')
    itv_date = models.CharField(max_length=150, blank=True, null=True, verbose_name='访谈日期')
    itv_stime = models.CharField(max_length=150, blank=True, null=True, verbose_name='开始时间')
    itv_etime = models.CharField(max_length=150, blank=True, null=True, verbose_name='结束时间')
    itv_duration = models.IntegerField(blank=True, null=False, default=0, verbose_name='访谈时长')
    itv_paid_duration = models.IntegerField(blank=True, null=False, default=0, verbose_name='计费时长')
    recorder = models.CharField(max_length=150, blank=True, null=True, verbose_name='录入人')
    interviewer = models.CharField(max_length=150, blank=True, null=True, verbose_name='约谈人')
    e_payment = models.FloatField(blank=True,null=False,default=0.0,verbose_name='专家付费总额')
    c_payment = models.FloatField(blank=True,null=False,default=0.0,verbose_name='客户收费总额')
    fee_index = models.FloatField(blank=True,null=False,default=1.0,verbose_name='咨费系数')
    knowledge = models.IntegerField(blank=True, null=False, default=0, verbose_name='知识范围')
    communication = models.IntegerField(blank=True, null=False, default=0, verbose_name='沟通能力')
    cooperation = models.IntegerField(blank=True, null=False, default=0, verbose_name='配合程度')
    avg_score = models.FloatField(blank=True,null=False,default=0.0,verbose_name='均分')
    itv_approach = models.CharField(max_length=150, blank=True, null=True, verbose_name='咨询方式')
    itv_remark = models.TextField(blank=True, null=True, verbose_name='备注')
    class Meta:
        managed = True
        ordering = ('-itv_date', '-itv_stime',)
        db_table = 'p_e_relationship'


    def __str__(self):
        return "{}-{}".format(self.pname,self.ename)

    def update_p2e_url(self):
        #print("==========projects/models.update_p2e_url()")
        return reverse('update_p2e_detail', args=[self.pteid,])

    def get_expert_company(self):
        # 返回最近一条工作经历的公司名
        return self.eid.get_company()

    def get_expert_bank_account(self):
        payment_methods = Payment.objects.filter(eid=self.eid)
        if payment_methods.exists() != 0:
            return payment_methods[0].bank
        return '未知'

clients/forms.py
from django import forms
from .models import *

class FindClientForm(forms.ModelForm):
    id = forms.IntegerField(label='客户ID',required=False)
    cname = forms.CharField(label='客户名称',max_length=150,required=False)

    class Meta:
        model = Client
        fields = ('cid','cname')

    def __init__(self, *args, **kwargs):
        super(FindClientForm, self).__init__(*args, **kwargs)
        for field_name in self.base_fields:
            field = self.base_fields[field_name]
            field.widget.attrs.update({"class":"form-control"})

class ClientForm(forms.ModelForm):
    # 该表单用于添加客户信息
    cname = forms.CharField(max_length=150,label='客户名称',required=False)
    bc_name = forms.CharField(max_length=50,required=False,label='主业务联系人')
    fc_name = forms.CharField(max_length=50,label='主财务联系人',required=False)
    ctype = forms.CharField(max_length=50,label='客户类型',required=False)
    cfee = forms.FloatField(label='咨费',required=False)
    cinfo = forms.CharField(label='客户信息', required=False)
    cpolicy = forms.CharField(label='收费政策',required=False)
    cremark = forms.CharField(label='备注', required=False)

    class Meta:
        model = Client
        fields = ('cname','bc_name','fc_name','ctype','cfee','cinfo','cpolicy','cremark')

    def __init__(self, *args, **kwargs):
        super(ClientForm, self).__init__(*args, **kwargs)
        for field_name in self.base_fields:
            field = self.base_fields[field_name]
            field.widget.attrs.update({"class":"form-control"})

class ClientUpdateForm(forms.ModelForm):
    # 该表单用于更新客户信息
    cname = forms.CharField(max_length=150, label='客户名称', required=False)
    bc_name = forms.CharField(max_length=50, required=False, label='主业务联系人')
    fc_name = forms.CharField(max_length=50, label='主财务联系人', required=False)
    ctype = forms.CharField(max_length=50, label='客户类型', required=False)
    cfee = forms.FloatField(label='咨费',required=False)
    cinfo = forms.CharField(label='客户信息', required=False)
    cpolicy = forms.CharField(label='收费政策', required=False)
    cremark = forms.CharField(label='备注', required=False)
    class Meta:
        model = Client
        fields = ('cname','bc_name','fc_name','ctype','cfee','cinfo','cpolicy','cremark')

    def __init__(self, *args, **kwargs):
        super(ClientUpdateForm, self).__init__(*args, **kwargs)
        for field_name in self.base_fields:
            field = self.base_fields[field_name]
            field.widget.attrs.update({"class": "form-control"})

class BCForm(forms.ModelForm):
    # 该表单用于添加/更新客户业务联系人信息
    bc_name = forms.CharField(label='姓名',max_length=50, required=False)
    bc_gender = forms.CharField(label='性别',max_length=10, required=False)
    bc_mobile = forms.CharField(label='电话',max_length=50, required=False)
    bc_wechat = forms.CharField(label='微信', max_length=50, required=False)
    bc_email = forms.CharField(label='邮箱',max_length=50, required=False)
    bc_position = forms.CharField(label='职位',max_length=50, required=False)

    class Meta:
        model = BusinessContact
        fields = ('bc_name','bc_gender','bc_mobile','bc_wechat','bc_email','bc_position')

    def __init__(self, *args, **kwargs):
        super(BCForm, self).__init__(*args, **kwargs)
        for field_name in self.base_fields:
            field = self.base_fields[field_name]
            field.widget.attrs.update({"class":"form-control"})


class FCForm(forms.ModelForm):
    # 该表单用于添加/更新客户财务联系人信息
    fc_name = forms.CharField(label='姓名',max_length=50, required=False)
    fc_gender = forms.CharField(label='性别',max_length=10, required=False)
    fc_mobile = forms.CharField(label='电话',max_length=50, required=False)
    fc_wechat = forms.CharField(label='微信', max_length=50, required=False)
    fc_email = forms.CharField(label='邮箱',max_length=50, required=False)
    fc_position = forms.CharField(label='职位',max_length=50, required=False)

    class Meta:
        model = FinancialContact
        fields = ('fc_name','fc_gender','fc_mobile','fc_wechat','fc_email','fc_position')

    def __init__(self, *args, **kwargs):
        super(FCForm, self).__init__(*args, **kwargs)
        for field_name in self.base_fields:
            field = self.base_fields[field_name]
            field.widget.attrs.update({"class":"form-control"})

clients/templates/clients/advanced_client_search.html
{% extends "clients/client_base.html" %}
{% block content %}
<div class="container-fluid" align="center">
    <div class="control-group">
        <h5>查找客户</h5>
    </div>

    <form class="form-horizontal" method="get" action="{% url 'advanced_client_search' %}">
        {% csrf_token %}
        <div class="control-group">
        <input class="form-control col-md-8" style="text-align: center;height:32px" type="text" aria-label="Search" name='cname' placeholder="客户名称" required>
       </div>
        <div class="control-group col-md-8" style="margin-top: 10px" align="center">

            <button type="submit" class="btn btn-success btn-sm">搜索</button>

        </div>
    </form>
</div>
{% endblock content %}

clients/templates/clients/client_detail.html
{% extends "clients/client_base.html" %}


{% block content %}
<div class="container-fluid">
    <div class="control-group">
        {% if perms.users.can_delete_client_info %}
        <h5>{{ client.cname }}&nbsp;
            <input type="button" class="btn btn-info btn-sm"  value="修改客户信息" onclick="window.location.href='{{ client.update_client_detail }}'">

            <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#deleteClient">删除</button>
            </h5>
            <div class="modal fade" id="deleteClient" tabindex="-1" role="dialog" aria-labelledby="deleteClientLabel">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>

                        </div>
                        <div class="modal-body">
                            <form>
                                <div class="form-group">
                                    <label class="control-label">确定要删除吗？</label>
                                </div>
                            </form>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">返回</button>
                            <button type="button" class="btn btn-primary btn-sm" onclick="window.location.href='{{ client.delete_client }}'">确认</button>
                        </div>
                    </div>
                </div>
            </div>

            {% if result == '删除失败' %}
            <div class="alert alert-danger" role="alert">
                {{ result }}
            </div>
            {% endif %}


        {% else %}
        <h5>{{ client.cname }}&nbsp
            {% if perms.users.can_change_client_info %}
                <input type="button" class="btn btn-info btn-sm"  value="修改客户信息" onclick="window.location.href='{{ client.update_client_detail }}'">
            {% endif %}
        </h5>
        {% endif %}
    </div>

    <div class="control-group">
        <table class="table table-condensed table-hover" width="100%" style="font-size:10px;table-layout: auto">
            <tr>
                <td>客户ID：{{ client.cid}}</td>
                <td>客户名称：{{ client.cname}}</td>
                <td>客户类型：{{client.ctype}}</td>

            </tr>

            <tr>
                <td>主业务联系人：{{client.bc_name}}</td>
                <td>主财务联系人：{{client.fc_name}}</td>
                <td>
                    {% if perms.users.can_view_cfee %}
                    咨费：{{ client.cfee }} 元
                    {% endif %}
                </td>
            </tr>
        </table>
    </div>
    <div class="control-group">
        <table class="table table-condensed table-hover" width="100%" style="font-size:10px;table-layout: auto">
            <caption>客户信息</caption>
            <tr>
                <td style="white-space: pre-line">收费政策：
                    {{ client.cpolicy }}
                </td>
            </tr>
            <tr>
                <td style="white-space: pre-line">客户信息：
                    {{ client.cinfo }}
                </td>
            </tr>
            <tr>
                <td style="white-space: pre-line">备注：
                    {{  client.cremark }}
                </td>
            </tr>
        </table>
    </div>

    <!--
    {% for p2e in p2es %}
    <p>
        <label style="font-weight: 700"></label>{{p2e}}&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp

    </p>
   {% endfor %}-->
    <div class="control-group">
        <h5>项目列表 &nbsp
            {% if perms.projects.add_project %}
            <input type="button" class="btn btn-success btn-sm"  value="添加" onclick="window.location.href='{{ client.client_add_project }}'">
            {% endif %}
        </h5>
        <table class="table table-condensed table-hover" width="100%" style="font-size:10px; max-height:50px">
            <caption>项目列表</caption>
            <thead style="background-color: whitesmoke">
            <tr>
                <th width="10%">项目ID</th>
                <th width="20%">项目名称</th>
                <th width="10%">客户对接人</th>
                <th width="10%">项目经理</th>
                <th width="15%">项目发布时间</th>
                <th width="15%">项目截止时间</th>
                <th width="6%"></th>

            </tr>
            </thead>
            <tbody>
            {% for project in projects %}
            <tr>
                <td>{{ project.pid }}</td>
                <td><a href="{{ project.get_project_detail }}">{{ project.pname }}</a></td>
                <td>{{ project.pm}}</td>
                <td>{{ project.person_in_charge }}</td>
                <td>{{ project.pcreatetime }}</td>
                <td>{{ project.pdeadline }}</td>
                {% if perms.projects.change_project %}
                <td>
                    <button type="button" class="btn btn-info btn-sm" onclick="window.location.href='{{ project.update_project_detail }}'">修改</button>
                </td>
                {% endif %}
            </tr>
            {% endfor %}

            </tbody>
        </table>
    </div>

    <div class="control-group">
        <h5>业务联系人 &nbsp
            {% if perms.users.can_add_client_bc_fc %}
            <input type="button" class="btn btn-success btn-sm"  value="添加" onclick="window.location.href='{{ client.client_add_bc }}'">
            {% endif %}
        </h5>
        <table class="table table-condensed table-hover" width="100%" style="font-size:10px; max-height:50px">
            <caption>业务联系人列表</caption>
            <thead style="background-color: whitesmoke">
            <tr>
                <th width="10%">姓名</th>
                <th width="5%">性别</th>
                <th width="15%">电话</th>
                <th width="15%">微信</th>
                <th width="15%">邮箱</th>
                <th width="10%">职位</th>
                <th width="12%"></th>

            </tr>
            </thead>
            <tbody>
            {% for bc in bc_list %}
            <tr class="info">
                <td>{{ bc.bc_name }}</td>
                <td>{{ bc.bc_gender }}</td>
                {% if perms.users.can_view_client_bc_fc_contact %}
                <td>{{ bc.bc_mobile}}</td>
                <td>{{ fc.fc_wechat}}</td>
                <td>{{ bc.bc_email }}</td>
                <td>{{ bc.bc_position }}</td>
                {% if perms.users.can_change_client_bc_fc_contact %}
                <td>
                    <button type="button" class="btn btn-info btn-sm" onclick="window.location.href='{% url 'bc_detail_update' bc.bc_id client.cid %}'">修改</button>

                    {% if perms.users.can_delete_client_bc_fc_contact %}
                    <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#deleteClientBC">删除</button>
                    <div class="modal fade" id="deleteClientBC" tabindex="-1" role="dialog" aria-labelledby="deleteClientBCLabel">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>

                                </div>
                                <div class="modal-body">
                                    <form>
                                        <div class="form-group">
                                            <label style="color: red;font-weight: 700" class="control-label">确定要删除吗？</label>
                                        </div>
                                    </form>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">返回</button>
                                    <button type="button" class="btn btn-primary btn-sm" onclick="window.location.href='{% url 'delete_client_bc' bc.bc_id client.cid %}'">确认</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% if result == '删除失败' %}
                        {{ result }}
                    {% endif %}

                    {% endif %}
                </td>
                {% endif %}
                {% endif %}
            </tr>
            {% endfor %}

            </tbody>
        </table>
    </div>
    <div class="control-group">
        <h5>财务联系人 &nbsp
            {% if perms.users.can_add_client_bc_fc %}
            <input type="button" class="btn btn-success btn-sm"  value="添加" onclick="window.location.href='{{ client.client_add_fc }}'">
            {% endif %}
        </h5>
        <table class="table table-condensed table-hover" width="100%" style="font-size:10px; max-height:50px">
            <caption>财务联系人列表</caption>
            <thead style="background-color: whitesmoke">
            <tr>
                 <th width="10%">姓名</th>
                <th width="5%">性别</th>
                <th width="15%">电话</th>
                <th width="15%">微信</th>
                <th width="15%">邮箱</th>
                <th width="10%">职位</th>
                <th width="12%"></th>
            </tr>
            </thead>
            <tbody>
            {% for fc in fc_list %}
            <tr class="info">
                <td>{{ fc.fc_name }}</td>
                <td>{{ fc.fc_gender }}</td>
                {% if perms.users.can_view_client_bc_fc_contact %}
                <td>{{ fc.fc_mobile}}</td>
                <td>{{ fc.fc_wechat}}</td>
                <td>{{ fc.fc_email }}</td>
                <td>{{ fc.fc_position }}</td>
                {% if perms.users.can_change_client_bc_fc_contact %}
                <td>
                    <button type="button" class="btn btn-info btn-sm" onclick="window.location.href='{% url 'fc_detail_update' fc.fc_id client.cid %}'">修改</button>

                    {% if perms.users.can_delete_client_bc_fc_contact %}
                    <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#deleteClientFC">删除</button>
                    <div class="modal fade" id="deleteClientFC" tabindex="-1" role="dialog" aria-labelledby="deleteClientFCLabel">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>

                                </div>
                                <div class="modal-body">
                                    <form>
                                        <div class="form-group">
                                            <label style="color: red;font-weight: 700" class="control-label">确定要删除吗？</label>
                                        </div>
                                    </form>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">返回</button>
                                    <button type="button" class="btn btn-primary btn-sm" onclick="window.location.href='{% url 'delete_client_fc' fc.fc_id client.cid %}'">确认</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% if result == '删除失败' %}
                        {{ result }}
                    {% endif %}

                    {% endif %}
                </td>
                {% endif %}
                {% endif %}
            </tr>
            {% endfor %}
            </tbody>
        </table>


        {% endblock content %}